# Generated by Django 2.2.7 on 2019-12-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20191210_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
